### ISSUE TITLE
`useDate` option

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#100]
# interface

## `useDate=false` 

```
  expiration?: Timestamp;
```

## `useDate=true` (default)

```
  expiration: Date;
```

# encode

## `useDate=false`

```
Timestamp.encode(message.expiration, writer.uint32(18).fork()).ldelim();
```

## `useDate=true` (default)

```
Timestamp.encode(toTimestamp(message.expiration), writer.uint32(18).fork()).ldelim();
```

# decode

## `useDate=false`

```
message.expiration = Timestamp.decode(reader, reader.uint32());
```

## `useDate=true` (default)

```
message.expiration = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
```

# from partial

## `useDate=false`

```
 message.expiration =
      object.expiration !== undefined && object.expiration !== null
        ? Timestamp.fromPartial(object.expiration)
        : undefined;
```

## `useDate=true` (default)

```
message.expiration = object.expiration ?? undefined;
```

# toJSON

## `useDate=false`

```
message.expiration !== undefined && (obj.expiration = fromTimestamp(message.expiration).toISOString());
```

## `useDate=true` (default)

```
message.expiration !== undefined && (obj.expiration = message.expiration.toISOString());
```

**Comment by webmaster128** [comment]
I would not make this a boolen flag but a `Timestamp` target type option. `Date` and `interface Timestamp` are two choices requested now. But an RFC3339 string would be a third sane option, maybe there are more. You could think of a datetime library that (in constrast to Date) operates on nanosecond precision.

ts-proto shows how the boolean flag became insufficient over time:

<img width="866" alt="Bildschirmfoto 2022-07-14 um 14 13 52" src="https://user-images.githubusercontent.com/2603011/178979835-bb750457-ca35-4885-9be4-40bd9c429786.png">

**Comment by pyramation** [comment]
great feedback, thanks @webmaster128 ! 

currently the draft is here https://github.com/osmosis-labs/telescope/pull/127/files

on the plugin options object, I'm using `useDate='date'` or `useDate='timestamp'`
