### ISSUE TITLE
Issue With Google protos

### ISSUE THREAD

**Issue by mpthomas** [osmosis-labs/telescope#107]
Bare with me as this is probably user error. I'm newish to ts projects and dependencies, so it's probably something simple. This is what I'm getting with my tsc build of a project I'm working on. I've spent quite a bit of time trying different things, including building the osmojs module in node_modules from scratch, which failed with a babel error on an 'unexpected unum'.

High level, I'm just trying to write a cli to do some swaps. I'm familiar enough with js to I think pull it off in ts, but don't know Go well enough to use the normal osmosis-sdk. If I'm headed down the wrong path I'm open to suggestions!

tsc output

```
node_modules/osmojs/types/proto/google/bundle.d.ts:664:53 - error TS2339: Property 'LoggingServiceV2ClientImpl' does not exist on type 'typeof import("<project-home>/node_modules/osmojs/types/proto/google/logging/v2/logging")'.

664             LoggingServiceV2ClientImpl: typeof _675.LoggingServiceV2ClientImpl;
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/osmojs/types/proto/google/bundle.d.ts:724:53 - error TS2339: Property 'MetricsServiceV2ClientImpl' does not exist on type 'typeof import("<project-home>/node_modules/osmojs/types/proto/google/logging/v2/logging_metrics")'.

724             MetricsServiceV2ClientImpl: typeof _674.MetricsServiceV2ClientImpl;
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/osmojs/types/proto/google/bundle.d.ts:1007:52 - error TS2339: Property 'ConfigServiceV2ClientImpl' does not exist on type 'typeof import('<project home>node_modules/osmojs/types/proto/google/logging/v2/logging_config")'.

1007             ConfigServiceV2ClientImpl: typeof _673.ConfigServiceV2ClientImpl;
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/osmojs/types/proto/google/bundle.d.ts:1102:43 - error TS2339: Property 'OperationsClientImpl' does not exist on type 'typeof import("<project home>/node_modules/osmojs/types/proto/google/longrunning/operations")'.

1102         OperationsClientImpl: typeof _676.OperationsClientImpl;
```

Applicable Code

```
import {
    AminoTypes,
    SigningStargateClient
} from '@cosmjs/stargate';
import { Registry } from '@cosmjs/proto-signing';
import { defaultRegistryTypes } from '@cosmjs/stargate';
import { OfflineSigner } from '@cosmjs/proto-signing'
import { osmosis } from 'osmojs';
````

tsconfig.json

```
{
  "compilerOptions": {
    "target": "es6",
    "allowJs": true,
    "noImplicitAny": false,
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "out",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node"
  },
  "include": ["src/*.ts"],
  "exclude": ["**/node_modules", "**/.*/"],
}
```

package.json dependencies (some probably unecessary, but whatevs at this point)

```
  "dependencies": {
    "@cosmjs/launchpad": "^0.27.1",
    "@cosmjs/proto-signing": "^0.28.4",
    "@cosmjs/stargate": "^0.28.4",
    "@keplr-wallet/types": "latest",
    "axios": "latest",
    "osmojs": "^0.4.45",
    "secretjs": "latest",
    "ts-node": "^10.8.0",
    "@protobufs/osmosis": "latest"
  }
```

**Comment by pyramation** [comment]
thanks for the note! I'll have an answer ASAP!

**Comment by pyramation** [comment]
looks like it was a vestage from the previous build — can you try this one:

```
osmojs@0.4.46
 ```

**Comment by pyramation** [comment]
also if you're building a CLI, take a look here at some methods that have been built on top of `osmojs` https://github.com/cosmology-finance/cosmology/tree/master/packages/cli/src/commands

**Comment by mpthomas** [comment]
Thanks for the fast response! Much better. It did still throw the error below. I commented out the single line for grins and it compiled successfully! Albeit the script pretty much does nothing, but it's progress 😄 

I'll definitely use the code in cosmology-finance.../cli/src/commands as inspiration. I'm doing my best not to resort to wrapper scripts to osmosisd, but we'll see.

If you're taking tips for your time, tell me where to send them. For now I'll leave this issue open because of the below error, but feel free to close as you wish. Thanks again!

```
node_modules/osmojs/types/proto/index.d.ts:13:15 - error TS2307: Cannot find module './google/bundle' or its corresponding type declarations.

13 export * from "./google/bundle";
                 ~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/osmojs/types/proto/index.d.ts:13
```

**Comment by pyramation** [comment]
thank you @mpthomas I believe I see the issue on this one! Will get this taken care of today!

**Comment by pyramation** [comment]
thanks @mpthomas this helped me discover a larger issue now documented here https://github.com/osmosis-labs/telescope/issues/108

if you try out the latest (currently `osmojs@0.4.49`) that file shouldn't be missing now. 

There may be other errors/warnings (I know there are some with duration types right now) — but I hope that doesn't stop your project from building. With babel + TS, the compiler works even if there are a few TS issues. Let me know if yours works!
