### ISSUE TITLE
documentation for amino encoding

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#114]
https://github.com/scrtlabs/secret.js/blob/master/DEVELOPERS.md

**Comment by pyramation** [comment]
@assafmo my guess is that, there is no standard for timestamp (date) or duration?

**Comment by assafmo** [comment]
Timestamp is a string of nanoseconds since unix epoch (UTC+0).

https://github.com/scrtlabs/secret.js/blob/7c5b302bc35b81fd7848fa4c18ddc8860fe65d8a/src/tx/ibc_transfer.ts#L62

**Comment by assafmo** [comment]
My guess is that duration is also a string of nanoseconds... Is there a Msg with a duration typed field?

**Comment by pyramation** [comment]
> https://github.com/scrtlabs/secret.js/blob/7c5b302bc35b81fd7848fa4c18ddc8860fe65d8a/src/tx/ibc_transfer.ts#L62

do you think there's a reason it's just `toString()` here?
https://github.com/cosmos/cosmjs/blob/main/packages/stargate/src/modules/ibc/aminomessages.ts#L88

**Comment by pyramation** [comment]
> My guess is that duration is also a string of nanoseconds... Is there a Msg with a duration typed field?

In osmosis: 
https://github.com/osmosis-labs/osmojs/blob/main/packages/osmojs/src/proto/osmosis/lockup/tx.amino.ts#L48
https://github.com/osmosis-labs/osmojs/blob/main/packages/osmojs/src/proto/osmosis/lockup/tx.amino.ts#L62-L65

but I'm not sure it's a standard... I'm trying to figure out what other chains are doing. If they're not yet using it, perhaps osmosis' way should be so we can standardize the amino.

**Comment by assafmo** [comment]
> > My guess is that duration is also a string of nanoseconds... Is there a Msg with a duration typed field?
> 
> In osmosis: https://github.com/osmosis-labs/osmojs/blob/main/packages/osmojs/src/proto/osmosis/lockup/tx.amino.ts#L48 https://github.com/osmosis-labs/osmojs/blob/main/packages/osmojs/src/proto/osmosis/lockup/tx.amino.ts#L62-L65
> 
> but I'm not sure it's a standard... I'm trying to figure out what other chains are doing. If they're not yet using it, perhaps osmosis' way should be so we can standardize the amino.

Duration & Amino are defined in cosmos-sdk, so I imagine what's working for Osmosis will work everywhere else

**Comment by assafmo** [comment]
Okay so [Duration in proto](https://github.com/enigmampc/cosmos-sdk/blob/ac08f6c7e0/proto/cosmos/feegrant/v1beta1/feegrant.proto#L39) leads [here](https://github.com/enigmampc/cosmos-sdk/blob/ac08f6c7e0/x/feegrant/feegrant.pb.go#L100) which leads [here](https://pkg.go.dev/time?utm_source=gopls#Duration), so Duration is `int64` which is a string

**Comment by assafmo** [comment]
Re timeout_timestamp in MsgTransfer, specifically here [it's uint64](https://github.com/cosmos/ibc-go/blob/46e02064/proto/ibc/applications/transfer/v1/tx.proto#L38-L40) and not `google.protobuf.Timestamp`. I beleive that `google.protobuf.Timestamp` converts to an RFC 3339 string with a timezone of UTC+0 ([example](https://github.com/tendermint/tendermint/blob/2f231ceb9/libs/json/encoder_test.go#L36-L38)).

**Comment by assafmo** [comment]
Updated DEVELOPERS.md: https://github.com/scrtlabs/secret.js/commit/a1d3636b81278b20da4ef122b7c54182ea622d36 :grimacing:

**Comment by pyramation** [comment]
> Is this working? From the docs [this](https://github.com/cosmos/cosmjs/blob/3222172e6a5bbd95a455f73020c613dbbed9acd1/packages/stargate/src/modules/ibc/aminomessages.ts#L84) has to be "0" if undefined ("0" is working for me in production).

I've only tried it by specifying `timeoutTimestamp`. https://github.com/cosmology-tech/cosmology/blob/main/packages/cli/src/commands/ibc-transfer.ts#L218-L224 

I'll be testing this more: https://github.com/osmosis-labs/telescope/issues/141

**Comment by pyramation** [comment]
thank you so much @assafmo your knowledge and research is greatly appreciated! this thread is GOLD!
