### ISSUE TITLE
Abstract away `Any` in the generated types

### ISSUE THREAD

**Issue by assafmo** [osmosis-labs/telescope#118]
Complex Msgs in cosmos-sdk usually have an `Any` field in them. It might be a good Idea to abstract this away from the users by recursively following `implements_interface` & `accepts_interface`.

For example:

- `allowance` is `Any` In `MsgGrantAllowance`: https://github.com/cosmos/cosmos-sdk/blob/v0.45.4/proto/cosmos/feegrant/v1beta1/tx.proto#L33
- Then you need to look at the `accepts_interface` and see that it's `FeeAllowanceI`
- Then lookup anything that is `implements_interface` for `FeeAllowanceI` and find all of these:
  - `BasicAllowance`: https://github.com/cosmos/cosmos-sdk/blob/v0.45.4/proto/cosmos/feegrant/v1beta1/feegrant.proto#L14-L27
  - `PeriodicAllowance`: https://github.com/cosmos/cosmos-sdk/blob/v0.45.4/proto/cosmos/feegrant/v1beta1/feegrant.proto#L29-L54
  - `AllowedMsgAllowance`: https://github.com/cosmos/cosmos-sdk/blob/v0.45.4/proto/cosmos/feegrant/v1beta1/feegrant.proto#L56-L66

Then the Typescript output should probably look like this:

```ts
/**
 * MsgGrantAllowance adds permission for Grantee to spend up to Allowance
 * of fees from the account of Granter.
 */
interface MsgGrantAllowance {
  granter: string;
  grantee: string;
  allowance: BasicAllowance | PeriodicAllowance | AllowedMsgAllowance;
}

/**
 * BasicAllowance implements Allowance with a one-time grant of tokens
 * that optionally expires. The grantee can use up to SpendLimit to cover fees.
 */
interface BasicAllowance {
  /**
   * spend_limit specifies the maximum amount of tokens that can be spent
   * by this allowance and will be updated as tokens are spent. If it is
   * empty, there is no spend limit and any amount of coins can be spent.
   */
  spendLimit: Coin[];
  /** expiration specifies an optional time when this allowance expires */
  expiration?: Timestamp;
}

/**
 * PeriodicAllowance extends Allowance to allow for both a maximum cap,
 * as well as a limit per time period.
 */
interface PeriodicAllowance {
  /** basic specifies a struct of `BasicAllowance` */
  basic?: BasicAllowance;
  /**
   * period specifies the time duration in which period_spend_limit coins can
   * be spent before that allowance is reset
   */
  period?: Duration;
  /**
   * period_spend_limit specifies the maximum number of coins that can be spent
   * in the period
   */
  periodSpendLimit: Coin[];
  /** period_can_spend is the number of coins left to be spent before the period_reset time */
  periodCanSpend: Coin[];
  /**
   * period_reset is the time at which this period resets and a new one begins,
   * it is calculated from the start time of the first transaction after the
   * last period ended
   */
  periodReset?: Timestamp;
}

/** AllowedMsgAllowance creates allowance only for specified message types. */
export interface AllowedMsgAllowance {
  /** allowance can be any of basic and filtered fee allowance. */
  allowance?: BasicAllowance | PeriodicAllowance | AllowedMsgAllowance;
  /** allowed_messages are the messages for which the grantee has the access. */
  allowedMessages: string[];
}
```

(BTW I'm still not sure how to handle optional fields, as some of them are definitely not optional)

**Comment by assafmo** [comment]
For reference, here's how it looks when generated with ts-proto:

```diff
/**
 * MsgGrantAllowance adds permission for Grantee to spend up to Allowance
 * of fees from the account of Granter.
 */
interface MsgGrantAllowance {
  granter: string;
  grantee: string;
-  allowance: BasicAllowance | PeriodicAllowance | AllowedMsgAllowance;
+  allowance?: Any;
}

/**
 * BasicAllowance implements Allowance with a one-time grant of tokens
 * that optionally expires. The grantee can use up to SpendLimit to cover fees.
 */
interface BasicAllowance {
  /**
   * spend_limit specifies the maximum amount of tokens that can be spent
   * by this allowance and will be updated as tokens are spent. If it is
   * empty, there is no spend limit and any amount of coins can be spent.
   */
  spendLimit: Coin[];
  /** expiration specifies an optional time when this allowance expires */
  expiration?: Timestamp;
}

/**
 * PeriodicAllowance extends Allowance to allow for both a maximum cap,
 * as well as a limit per time period.
 */
interface PeriodicAllowance {
  /** basic specifies a struct of `BasicAllowance` */
  basic?: BasicAllowance;
  /**
   * period specifies the time duration in which period_spend_limit coins can
   * be spent before that allowance is reset
   */
  period?: Duration;
  /**
   * period_spend_limit specifies the maximum number of coins that can be spent
   * in the period
   */
  periodSpendLimit: Coin[];
  /** period_can_spend is the number of coins left to be spent before the period_reset time */
  periodCanSpend: Coin[];
  /**
   * period_reset is the time at which this period resets and a new one begins,
   * it is calculated from the start time of the first transaction after the
   * last period ended
   */
  periodReset?: Timestamp;
}

/** AllowedMsgAllowance creates allowance only for specified message types. */
export interface AllowedMsgAllowance {
  /** allowance can be any of basic and filtered fee allowance. */
-  allowance: BasicAllowance | PeriodicAllowance | AllowedMsgAllowance;
+  allowance?: Any;
  /** allowed_messages are the messages for which the grantee has the access. */
  allowedMessages: string[];
}
```

**Comment by assafmo** [comment]
From looking in the cosmos-sdk code there aren't a lot of these, but by abstracting this away from devs Telescope will make it easy for them to use complex Msgs and will empower blockchain devs to create complex Msgs in the future knowing that it'll not be hard for devs to use them. 

![image](https://user-images.githubusercontent.com/22766533/176420107-9bee33dc-78d4-400f-8e0f-84441db786d3.png)

**Comment by pyramation** [comment]
https://github.com/cosmos/cosmos-proto/issues/5

**Comment by pyramation** [comment]
In `bank.proto` there is an URL for `implements`:

- `option (cosmos_proto.implements_interface) = "*github.com/cosmos/cosmos-sdk/x/bank/migrations/v040.SupplyI";`

**Comment by pyramation** [comment]
## `cosmos_proto.accepts_interface`

https://github.com/regen-network/cosmos-proto#accepts_interface

> An informational extension to be added to `google.protobuf.Any` fields to indicate which interface that field accepts. The interface name should be independent of any programming language and either be unqualified to indicate the current package of fully-qualified to indicate another protobuf package.

```proto
message SomeContainer {
    google.protobuf.Any some_interface = 1 [(cosmos_proto.accepts_interface) = "SomeInterface"];
}

message AnotherContainer {
    google.protobuf.Any another_interface = 1 [(cosmos_proto.accepts_interface) = "another.package.AnotherInterface"];
}
```

## `implements_interface`

https://github.com/regen-network/cosmos-proto#implements_interface

> An informational extension to be added to messages to indicate which interface that message implements. The interface name should be independent of any programming language and either be unqualified to indicate the current package of fully-qualified to indicate another protobuf package.

```proto
message A {
    option (cosmos_proto.implements_interface) = "SomeInterface";
    int64 x = 1;
}

message B {
    option (cosmos_proto.implements_interface) = "another.package.AnotherInterface";
    double x = 1;
}
```

**Comment by assafmo** [comment]
So things just became more complicated. Reposting from Discord:

Hi all, I have a question about the protobuf definitions of `MsgSubmitProposal`. 👋 

In [`MsgSubmitProposal`](https://github.com/scrtlabs/cosmos-sdk/blob/ac08f6c7e0/proto/cosmos/gov/v1beta1/tx.proto#L29-L44) content is `(cosmos_proto.accepts_interface) = "Content"`, but only [`TextProposal`](https://github.com/scrtlabs/cosmos-sdk/blob/ac08f6c7e0/proto/cosmos/gov/v1beta1/gov.proto#L44-L53) is `(cosmos_proto.implements_interface) = "Content"`.

In practice there are at least 7 proposal types that I manged to find by hand, so my question is how can client library effectively find them?
1. [`SoftwareUpgradeProposal`](https://github.com/scrtlabs/cosmos-sdk/blob/ac08f6c7e0/proto/cosmos/upgrade/v1beta1/upgrade.proto#L45-L54)
2. [`CancelSoftwareUpgradeProposal`](https://github.com/scrtlabs/cosmos-sdk/blob/ac08f6c7e0/proto/cosmos/upgrade/v1beta1/upgrade.proto#L56-L64)
3. [`TextProposal`](https://github.com/scrtlabs/cosmos-sdk/blob/ac08f6c7e0/proto/cosmos/gov/v1beta1/gov.proto#L44-L53)
4. [`ParameterChangeProposal`](https://github.com/scrtlabs/cosmos-sdk/blob/ac08f6c7e0/proto/cosmos/params/v1beta1/params.proto#L9-L17)
5. [`CommunityPoolSpendProposal`](https://github.com/scrtlabs/cosmos-sdk/blob/ac08f6c7e0/proto/cosmos/distribution/v1beta1/distribution.proto#L111-L124)

And two more in ibc-go:
6. [`ClientUpdateProposal`](https://github.com/cosmos/ibc-go/blob/46e02064/proto/ibc/core/client/v1/client.proto#L39-L54)
7. [`UpgradeProposal`](https://github.com/cosmos/ibc-go/blob/46e02064/proto/ibc/core/client/v1/client.proto#L56-L74)

Seems to me that they're all manually implementing the [`Content`](https://github.com/scrtlabs/cosmos-sdk/blob/ac08f6c7e0/x/gov/legacy/v036/types.go#L40-L47) interface in Go after being derived from protobuf, and that's what ultimately decides if it's a valid proposal type or not.

Also seems like [`CommunityPoolSpendProposalWithDeposit`](https://github.com/enigmampc/cosmos-sdk/blob/ac08f6c7e0/proto/cosmos/distribution/v1beta1/distribution.proto#L154-L165) is defined but doesn't implement the `Content` interface.

Would love to get some feedback and more info on this. 🙏

**Comment by pyramation** [comment]
@ValarDragon one question I have — would it be a breaking change to add the `(cosmos_proto.implements_interface) = "Content"` to any proposal message? 

It seems that there was a convention, but perhaps it didn't get followed. If this would be a non-breaking change, adding this option would allow us to automate all the proposal serialization logic.

**Comment by pyramation** [comment]
we also need to figure out where in exported `.proto` files the `Content` and `Authorization` message are. 

- `Content` https://github.com/cosmos/cosmos-sdk/blob/main/x/gov/types/v1beta1/content.go#L9-L16
- `Authorization` https://github.com/cosmos/cosmos-sdk/blob/main/x/authz/authorizations.go#L11-L25

@faddat @nghuyenthevinh2000 do you know if the cosmos-sdk protos export these two objects to `.proto` files?

**Comment by ValarDragon** [comment]
> (cosmos_proto.implements_interface) = "Content"

This should be possible and not a breaking change to do, as far as I understand! I'd test it on a node before releasing, but that should be easy to do

**Comment by pyramation** [comment]
some examples I've found in the wild:

```js

export const createSubmitProposalMsg = (
    typeUrl,
    title,
    description,
    proposer,
    deposit,
    denom,
) => {
    const msgSubmitProposal = {
        content: {
            typeUrl: typeUrl,
            value: gov_1.TextProposal.encode(gov_1.TextProposal.fromPartial({
                title: title,
                description: description,
            })).finish(),
        },
        initialDeposit: coins(deposit, denom),
        proposer: proposer
    }

    const msg = {
        typeUrl: "/cosmos.gov.v1beta1.MsgSubmitProposal",
        value: msgSubmitProposal,
    }

    return msg
}
```

**Comment by JakeHartnell** [comment]
Really glad to see this... this is the kind of annoying stuff we have to do to encode nest proto messages in JS right now: https://github.com/DA0-DA0/dao-dao-ui/blob/940462a5210c507a731289b3dc2cdcc36299c33d/packages/utils/messages.ts#L205

**Comment by pyramation** [comment]
due to infinite recursion of the authz messages types — pretty certain we need to re-write how amino types are encoded: this will be more maintainable as well: https://github.com/osmosis-labs/telescope/issues/49

**Comment by pyramation** [comment]
related https://github.com/osmosis-labs/osmojs/issues/5

**Comment by pyramation** [comment]
- [ ] ARRAYS
```
[(cosmos_proto.accepts_interface) = "sdk.Msg, authz.Authorization"];
```

- [ ] URIs

```
(cosmos_proto.implements_interface) = "*github.com/cosmos/cosmos-sdk/x/bank/migrations/v040.SupplyI";
``

**Comment by pyramation** [comment]
tracking https://github.com/osmosis-labs/telescope/pull/272

**Comment by pyramation** [comment]
@assafmo making some progress, these are auto-generated decoders:

```js
import { DepositDeploymentAuthorization as DepositDeploymentAuthorization1 } from "../../../akash/deployment/v1beta1/authz";
import { DepositDeploymentAuthorization as DepositDeploymentAuthorization2 } from "../../../akash/deployment/v1beta2/authz";
import { SendAuthorization } from "../../bank/v1beta1/authz";
import { StakeAuthorization } from "../../staking/v1beta1/authz";


export const Authorization_InterfaceDecoder = (input: _m0.Reader | Uint8Array): DepositDeploymentAuthorization1 | DepositDeploymentAuthorization2 | GenericAuthorization | SendAuthorization | StakeAuthorization | Any => {
  const reader = input instanceof _m0.Reader ? input : new _m0.Reader(input);
  const data = Any.decode(reader, reader.uint32());

  switch (data.typeUrl) {
    case "/akash.deployment.v1beta1.DepositDeploymentAuthorization":
      return DepositDeploymentAuthorization1.decode(data.value);

    case "/akash.deployment.v1beta2.DepositDeploymentAuthorization":
      return DepositDeploymentAuthorization2.decode(data.value);

    case "/cosmos.authz.v1beta1.GenericAuthorization":
      return GenericAuthorization.decode(data.value);

    case "/cosmos.bank.v1beta1.SendAuthorization":
      return SendAuthorization.decode(data.value);

    case "/cosmos.staking.v1beta1.StakeAuthorization":
      return StakeAuthorization.decode(data.value);

    default:
      return data;
  }
};
```
