### ISSUE TITLE
Swapping assets programmatically on osmosis testnet with OsmoJS

### ISSUE THREAD

**Issue by najienka** [osmosis-labs/telescope#124]
Please is there a detailed example or docs somewhere on how to programmatically swap assets on the testnet. 
In the documentation online, it's not clear on how to setup the OfflineSigner and send the message to the testnet or using the client to send the message to the testnet.
https://docs.osmosis.zone/developing/tools/osmojs.html#composing-messages 
https://github.com/osmosis-labs/telescope/tree/master/packages/osmojs/docs

Also, is it possible generate the raw transaction for example, on a backend script and send it chain from a Keplr wallet?

Any help will be appreciated, thanks.

**Comment by pyramation** [comment]
hey @najienka we just added some docs for `osmojs` [here](https://github.com/osmosis-labs/osmojs) 

It should cover how to setup all of the things for composing and broadcasting messages.

please check this out and make any new issues there, we're going to migrate osmosjs over to that repo.

cheers and thanks!
