### ISSUE TITLE
multi-package LCD Clients v2

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#155]
the first approach to making multi-package LCD clients can easily create naming collisions. It works, but we can improve. [see PR here](https://github.com/osmosis-labs/telescope/pull/154) and example client [here](https://github.com/osmosis-labs/telescope/blob/ecc25362d7ab35eb788199bc2de79f9629894f15/__fixtures__/output1/osmosis/lcd.ts)

For the v2, improved version, seems that a better approach is similar to how secret.js handles their RPC clients:

https://github.com/scrtlabs/secret.js/blob/master/src/secret_network_client.ts#L670-L686

- [x] uses objects with scoped levels that can represent modules
- [x] the leaf nodes are classes
- [x] instantiates these classes so they're ready for use

## example code 

```js
const lcd = {
    cosmos: {
        bank: {
            v1beta1: new cosmos.bank.v1beta1.LCDClient({rpcEndpoint})
        },
        gov: {
            v1beta1: new cosmos.gov.v1beta1.LCDClient({rpcEndpoint})
        }
    },
    osmosis: {
        gamm: {
            v1beta1: new osmosis.gamm.v1beta1.LCDClient({rpcEndpoint})
        }
    }
};
```

## example settings

In this example, it would make an aggregated client made of these three modules

```js
telescope({
    protoDirs,
    outPath,
    options: {
        lcd: {
            packages: [
                'cosmos.bank.v1beta1',
                'cosmos.gov.v1beta1',
                'osmosis.gamm.v1beta1'
            ]
        }
    }
});
```

cc @assafmo

**Comment by pyramation** [comment]
also example of out how types work using `await import`:

```js
export const lcd = async ({ restEndpoint }) => ({
    bank: new (
        await import("./proto/cosmos/bank/v1beta1/query.lcd")
    ).LCDQueryClient({ restEndpoint }),
    gov: new (
        await import("./proto/cosmos/gov/v1beta1/query.lcd")
    ).LCDQueryClient({ restEndpoint }),
    gamm: new (
        await import("./proto/osmosis/gamm/v1beta1/query.lcd")
    ).LCDQueryClient({ restEndpoint })
});

const main = async () => {
    const obj = await lcd({ restEndpoint: 'https://lcd-osmosis.whispernode.com/' });
}
```

**Comment by pyramation** [comment]
https://github.com/osmosis-labs/telescope/pull/156

**Comment by assafmo** [comment]
Looks good! As long as there are no name collisions I'd use `bank` instead of `cosmos.bank.v1beta1`
