### ISSUE TITLE
DeepPartial vs Partial

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#187]
from telegram:

> ...can't compile my proto because Long.fromValue() in ts, it can't casting loing type in DeepPartial... Can you help me? Below is sample code.

```js
fromPartial(object: DeepPartial<TxResponse>): TxResponse {
    // ...
    message.height = object.height !== undefined && object.height !== null ? Long.fromValue(object.height) : Long.ZERO;
    // ....
}
```

> Error is occured in Long.fromValue(object.height) bacause it can cast only Long type but object.height is not a Long type in my environment. It is declared Long type, but in DeepPartial<TxResponse> maybe it is not just Long type...

> But it is correctly compiled with changing DeepPartial to Partial.

**Comment by pyramation** [comment]
should close with #189

**Comment by boosik** [comment]
Thank you for your support Dan!

**Comment by pyramation** [comment]
sure thing! Happy to help out :)

**Comment by webmaster128** [comment]
I just ran into this as well in cosmjs-types. There we need the deep partial feature. When comparing the DeepPartial implementation of telescope and ts-proto I found this:

<img width="429" alt="Bildschirmfoto 2022-11-24 um 17 45 23" src="https://user-images.githubusercontent.com/2603011/203833910-f70287a3-ee08-43ec-85bc-3cd6937654da.png">

This seems to be a special case that avoids dismanttling the Long type into its incredients and making everything optional which is not optional.

**Comment by pyramation** [comment]
@webmaster128  try this one!

```
Successfully published:
 - @osmonauts/telescope@0.79.0
```

**Comment by webmaster128** [comment]
https://github.com/osmosis-labs/telescope/commit/6af71005869f2d30f2ede526c53f626cc84d0f9b is all we need here. Can be closed IMO.

Am I right that Long can be disabled via configuration these days? Then I would consider emitting those two lines only when Long is used. But that's a nice to have.

**Comment by webmaster128** [comment]
In https://github.com/confio/cosmjs-types/pull/48 you see the upgrade and that I can remove my patch now and the generated code stays intact. Great stuff.

**Comment by pyramation** [comment]
> [6af7100](https://github.com/osmosis-labs/telescope/commit/6af71005869f2d30f2ede526c53f626cc84d0f9b) is all we need here. Can be closed IMO.
> 
> Am I right that Long can be disabled via configuration these days? Then I would consider emitting those two lines only when Long is used. But that's a nice to have.

Not yet! but we are tracking [getting rid of the `Long` dependency here](https://github.com/osmosis-labs/telescope/issues/119)

**Comment by pyramation** [comment]
> In [confio/cosmjs-types#48](https://github.com/confio/cosmjs-types/pull/48) you see the upgrade and that I can remove my patch now and the generated code stays intact. Great stuff.

Amazing! Now we can close this issue, yay 🙏🏻
