### ISSUE TITLE
how to manage LCD/RPC responses when `keepCase:false`

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#197]
to fix #194 we added the `keepCase` option. 

While setting `keepCase:true` fixes #194 , some devs may like to use `camelCase` for properties. The question is, how should we approach this. 

One idea is to create a recursive rendered interface (similar to our amino types) specifically for LCD/RPC responses.

**Comment by pyramation** [comment]
hey @haveanicedavid — you should be able to do `keepCase: false` now, and the types will be properly encoded for LCD and RPC servers!

The latest version has updates if you want to try it. I could make the developer experience to use camelCase, but it's not necessary.

```
@osmonauts/telescope@0.24.2 
```

and try `keepCase: false` if you want to try the new stuff ;) 



details: we now support regular types and then SDK types. The SDK types are what the developer originally wrote in the SDK, and the regular types are camelCase types created by protobuf.js.

**Comment by haveanicedavid** [comment]
@pyramation oh that sounds great! Testing now - thanks for the heads up
