### ISSUE TITLE
`Duration`s are being typed incorrectly

### ISSUE THREAD

**Issue by NoahSaso** [osmosis-labs/telescope#211]
`Long`s are typed with a class but appear to be serialized as a string representing its value in seconds.

![image](https://user-images.githubusercontent.com/6721426/191154719-23c6026f-0016-443c-869f-0d9c5f0c4315.png)
![image](https://user-images.githubusercontent.com/6721426/191154727-38d9fb82-ccfa-4ade-bf3d-fca81625ad52.png)
![image](https://user-images.githubusercontent.com/6721426/191154740-5dc3c8c0-edb7-449c-9e22-67f13592488a.png)
![image](https://user-images.githubusercontent.com/6721426/191154747-aa9b84b4-772b-4950-a750-6f87281bdf3d.png)

**Comment by pyramation** [comment]
related https://github.com/osmosis-labs/telescope/issues/142

**Comment by NoahSaso** [comment]
oh yeah jk it's Duration not Long

**Comment by pyramation** [comment]
https://github.com/osmosis-labs/osmojs/issues/12

**Comment by pyramation** [comment]
please try the new release candidate to test this via osmojs:

```
osmojs@15.1.0-rc.1
```

example here https://github.com/cosmology-tech/cosmology/blob/main/packages/cli/src/commands/lock.ts#L113-L116

```js

  const msg = lockTokens({
    owner: account.address,
    coins,
    duration: Duration.fromPartial({
      seconds: Long.fromString(duration),
      nanos: 0
    })
  });
  ```
