### ISSUE TITLE
npm install failing: no version found for proto-parser

### ISSUE THREAD

**Issue by haveanicedavid** [osmosis-labs/telescope#221]
<img width="769" alt="CleanShot 2022-09-22 at 17 52 59@2x" src="https://user-images.githubusercontent.com/9052511/191870809-ef80b459-ec5d-4932-9ed0-e3a394e0f9eb.png">

Noticed a similar warning when running `yarn upgrade` on some of the project deps

**Comment by Stphill0** [comment]
Hi @haveanicedavid   kindly visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)
