### ISSUE TITLE
namespace and package not supported

### ISSUE THREAD

**Issue by demondayza** [osmosis-labs/telescope#245]
First off, thank you for this impressive package!

Im busy running the transpile step on our chains protobuf files and I am getting this error above. 

How would I address this ?  It appears on the surface to be a support issue for the protocol buffers but I may be wrong.

Can someone add some insight here?

**Comment by demondayza** [comment]
Hey Dan! Here is the is a repository with the proto files in question: https://github.com/demondayza/ProtoFilesforTelescopeFeedback

**Comment by pyramation** [comment]
hey @demondayza — I've found a solution locally to get everything to work. But I have a question, did you use the ignite CLI to create these? Why are all the modules in the global namespace?

A big issue with your protos is that your package will not be very portable. I can make an experimental option that will allow these to work, but I still want to point this out to help improve the interoperability of your project

https://github.com/ignite/cli/issues/2871 and this comment specifically https://github.com/ignite/cli/issues/2871#issuecomment-1264690290

**Comment by pyramation** [comment]
is it this one https://github.com/ixofoundation/ixo-blockchain/tree/main/proto ?

I'd love to do two things 1. make an issue to explain how to make `ixo` protos more interoperable. and 2. make an experimental flag to help you get the JS working for now. How does the sound?

**Comment by demondayza** [comment]
Hey @pyramation there is some legacy work behind the proto files themselves from a previous  developer so we welcome any and all advice to improve them with our current developers . You have the correct repository there absolutely and I encourage you to make a issue we can work with our side.

At the moment we are a couple weeks away from a chain version upgrade so this advice comes at the perfect time! 

Essentially we want what's best and this advice will go a long way in helping us do that. 

Thanks for the effort so far @pyramation this is what makes the cosmos ecosystem as cool as it is.

**Comment by pyramation** [comment]
awesome! made an issue here https://github.com/ixofoundation/ixo-blockchain/issues/272

**Comment by pyramation** [comment]
also @demondayza let me know if you need help with the telescope package — feel free to add me to it and I can help out.
