### ISSUE TITLE
Generate protofiles directly from a git repository url

### ISSUE THREAD

**Issue by srph** [osmosis-labs/telescope#257]
Amazing project here! Thanks for building and maintaining this tool.

Just wanted to ask if telescope at the moment supports / has plans to support generating protofiles directory from a git repo?

To elaborate, we could do something like `telescope({ protoDirs: 'https://github.com/username/project/path/to/proto' })

We don't necessarily generate proto files often, but I think this would greatly improve QOL - less copy-pasting.

**Comment by pyramation** [comment]
what many projects do is use git submodules. This is technically supported today. This is how cosmjs uses telescope 

https://github.com/confio/cosmjs-types/blob/2f5736e5a32093a04c9c0926fc8891b2483d23a8/scripts/codegen.js#L7-L12

**Comment by pyramation** [comment]
is this for stridejs? Btw, I would be happy to move the [stridejs](https://github.com/cosmology-tech/stridejs) package over to your organization and help set this up.

**Comment by srph** [comment]
Thanks so much @pyramation! I appreciate the offer, but hold that thought. I'll get back to you as we're on a tight schedule at the moment. 

Anyway for now, I'll close this PR.
