### ISSUE TITLE
gRPC gateway

### ISSUE THREAD

**Issue by pyramation** [osmosis-labs/telescope#288]
let's make a new plugin/option to emulate `protoc-gen-grpc-gateway-ts` for `protoc` in telescope

example https://github.com/scrtlabs/secret.js/commit/e1f0e11889f60814e0ab9ed4ea3470519a4995c8

**Comment by pyramation** [comment]
> grpc gateway need a proxy in client, how did secret implement in browser side?
- @liangping

@assafmo is there anything we need to note for this implementation in regards to proxy?

**Comment by pyramation** [comment]
https://twitter.com/assafmo/status/1543577752657428486?s=20&t=Ji1fQide9ILE_K5UYb-oZQ

**Comment by assafmo** [comment]
The proxy is already built into the Cosmos SDK, on the client side it's just as simple as using a REST API
