### ISSUE TITLE
Error when run telescope install - TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by simplyrider** [osmosis-labs/telescope#298]
Hello!

When I run ```telescope install``` inside a telescope generated folder I'm faccing this issue:

![image](https://user-images.githubusercontent.com/96726225/214951816-51d6d074-4dc9-422d-ba84-dc95ef1f1d04.png)

Any thoughts about this?

I followed this video https://www.youtube.com/watch?v=wQ-CgZxhmC8&list=PL-lMkVv7GZwyQaK6bp6kMdOS5mzosxytC&index=2, but don't worked to me.

**Comment by pyramation** [comment]
what version of `node`, `npm` (or `yarn`) are you using?

**Comment by simplyrider** [comment]
> what version of `node`, `npm` (or `yarn`) are you using?

Hi @pyramation! Thanks for your reply.

Please see the image below:
![image](https://user-images.githubusercontent.com/96726225/215087842-387f9816-8e24-42f0-aba4-85be1b8e4f84.png)

**Comment by simplyrider** [comment]
The solution is don't use windows, because the \ is not recognized by library to build a path : C:\users\rider\path/whatever/package.json

Runed perfectly in linux, that uses / on path address:
home/rider/whatever/package.json.

Please, update the docs to avoid this error on windows users. For newbies guys like me :)
