### ISSUE TITLE
Long.fromValue causing overflow

### ISSUE THREAD

**Issue by chismo950** [osmosis-labs/telescope#327]
When we generate ts client using the telescope, we encounter a overflow issue, the cause is that we have a denom call ausdc, and 1 USDC = 10^18 ausdc, when 80000 USDC convert to "80000000000000000000000" the overflow happened on Long.fromValue(value.amount).toString() and it bacame "-3529047678325358592"

There are many Long.fromValue, for example at src/codegen/cosmos/staking/v1beta1/tx.amino.ts at line 116:

```
value: {
  denom: value.denom,
  amount: Long.fromValue(value.amount).toString()
}
```

So why not just pass value.amount, why use Long.fromValue to convert it again?

**Comment by Zetazzz** [comment]
Hi, we just merged code of getting rid of long in Telescope, you can try the option:

        typingsFormat: {
            ...
            longLibrary: 'bigint',
        },

Thx for your feedback and patience!

**Comment by pyramation** [comment]
we just renamed it `prototypes.typingsFormat.num64` 

cc @chismo950
