### ISSUE TITLE
Allow excluding protofiles files by pattern or directory

### ISSUE THREAD

**Issue by webmaster128** [osmosis-labs/telescope#334]
I'm using the collowing script to tun telescope: https://github.com/confio/cosmjs-types/blob/9db41ddcc7633f28f38babdc814e77b596315601/scripts/codegen.js

Now when upgrading to Cosmos SDK 0.47, I'd like to exlude all proto files of cosmos/autocli. I could list them individually but for better script maintainability it would be great if I could exclude the whole folder or a pattern like `cosmos/autocli/**/*.proto`.

**Comment by pyramation** [comment]
yea this is a great idea, for now, does this work: https://github.com/pyramation/telescope-decoders/blob/f854a589c7085f68bbc460e36522c3f39e0cb4b3/scripts/codegen.js#L34

**Comment by webmaster128** [comment]
That works, thank you!

However, also for packages it would be great to have prefix matching to be able to exlude `cosmos.autocli` or `cosmos.autocli.*`

**Comment by pyramation** [comment]
working on this! 

also will add this for later:
- [ ] consider deprecating `patterns` in favor of packages and protos supporting minimatch
