### ISSUE TITLE
recursive lookup results in max callstack error

### ISSUE THREAD

**Issue by kombos** [osmosis-labs/telescope#349]
We're trying to generate telescope ts endpoints for our chain (AssetMantle), codebase provided here to reproduce the issue: 
https://github.com/kombos/telescopeExample/tree/newTelescope1 

on running 'yarn codegen', it is throwing the error: 
`RangeError: maximum call stack size exceeded`

These are the specific amino related config values set: 
useRecursiveV2encoding: true (inside aminoEncoding)
toAmino: true, (inside methods)
fromAmino: true, (inside methods)

please find the full error log below: 
![image](https://user-images.githubusercontent.com/18464450/233606473-6d08aabd-15d3-4b94-b695-31efb86363b0.png)

**Comment by Zetazzz** [comment]
Hi, got it, thx for feedback! will give it a check soon

**Comment by Zetazzz** [comment]
Hi

I tried:

downloaded https://github.com/kombos/telescopeExample/tree/newTelescope1
updated telescope to latest: "@osmonauts/telescope": "^0.94.0",
yarn and yarn codegen, and it's done without error.
and just in case missing anything, I also removed       exceptions: AMINO_MAP,
and still done without error.

So I think maybe you can try updating telescope to latest

Thank you very much!

**Comment by kombos** [comment]
thanks for the pointer. this can be closed now.
