### ISSUE TITLE
Types folder missing when importing telescope modules from published npm package

### ISSUE THREAD

**Issue by kombos** [osmosis-labs/telescope#358]
hi, i've created telescope generated modules of our AssetMantle chain, the repo for which exists [here](https://github.com/kombos/telescopeExample/tree/newTelescope1). I've then published the package to npm [here](https://www.npmjs.com/package/@kombos/telescopeexample). On importing this npm package to my webApp, I notice that I'm unable to import the signing clients (getSigningAssetmantleClient) or any assetmantle modules. On investigating I found out that inside @kombos/telescopeexample folder in node_modules, there is no 'types' folder generated (see screenshot):
<img width="245" alt="image" src="https://user-images.githubusercontent.com/18464450/235947332-de62dfa9-d1f1-4e75-98f2-ae80eaf53b2f.png">

any ideas why the types folder is missing on publishing to npm and importing? tx.

**Comment by pyramation** [comment]
https://github.com/kombos/telescopeExample/blob/60a9c10847c522580f2c8ca52cd819cf0b178569/package.json#L24

you should run `yarn build:ts` to create the types

**Comment by hoangdv2429** [comment]
fixed
