### ISSUE TITLE
Timestamp field must not be undefined in createBaseXyz()

### ISSUE THREAD

**Issue by webmaster128** [osmosis-labs/telescope#403]
In Telescope 0.99.0, I get the folling compilation issue for type

```ts
/** Header defines the structure of a Tendermint block header. */
export interface Header {
  /** basic block info */
  version: Consensus;
  chainId: string;
  height: Long;
  time: Timestamp;
  /** prev block info */
  lastBlockId: BlockID;
  /** hashes of block data */
  lastCommitHash: Uint8Array;
  dataHash: Uint8Array;
  /** hashes from the app output from the prev block */
  validatorsHash: Uint8Array;
  /** validators for the next block */
  nextValidatorsHash: Uint8Array;
  /** consensus params for current block */
  consensusHash: Uint8Array;
  /** state after txs from the previous block */
  appHash: Uint8Array;
  lastResultsHash: Uint8Array;
  /** consensus info */
  evidenceHash: Uint8Array;
  /**
   * proposer_address is the original block proposer address, formatted as a Bech32 string.
   * In Tendermint, this type is `bytes`, but in the SDK, we convert it to a Bech32 string
   * for better UX.
   */
  proposerAddress: string;
}
```

<img width="581" alt="Bildschirmfoto 2023-06-29 um 15 55 54" src="https://github.com/osmosis-labs/telescope/assets/2603011/a5fd40c2-cc00-4992-b5bb-9818dba5ee24">

This is because `time: Timestamp;` must not be undefined. The correct default value is `Timestamp.fromPartial({})`.

**Comment by pyramation** [comment]
if it's undefined, I'm guessing is this the defaults for null, that we recently changed? or do the protos not indicate the proper nullability?

@Zetazzz I would suggest we use ts-disable if there is a discrepancy between the protos and the expected types. If we're not in a weird bind like that, then let's see how to fix it and maybe where to update the protos, etc.

**Comment by webmaster128** [comment]
I think this case is missing in the recent PR https://github.com/osmosis-labs/telescope/pull/400. The `time: Timestamp;` was `time: Timestamp | undefined;` before https://github.com/osmosis-labs/telescope/pull/392.

**Comment by Zetazzz** [comment]
Hi, I tried to compile with this. I guess for now if we don't use strict mode (disable strict null check), there wouldn't be this error.

**Comment by hoangdv2429** [comment]
@webmaster128 I push a fix for this. Can you have a look

**Comment by hoangdv2429** [comment]
@webmaster128  if you face any problem using Telescope, please ping me and we'll try to resolve it.

**Comment by hoangdv2429** [comment]
@webmaster128 do you think we can close this ?

**Comment by webmaster128** [comment]
I don't have the chance to test it right now but it seems like #416 fixed it. So let's assume it works. Will let you know if there is still issues. Thank you!
